env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  jsx-quotes:
    - error
    - prefer-single
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react/jsx-uses-react:
    - error
  max-len:
    - error
    - 80