root: true
env:
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: off
  max-len:
    - error
    - 80
  object-curly-spacing:
    - error
    - always
