language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- yarn install
script:
- yarn test -- --coverage
- yarn run submit-coverage
- yarn run build
deploy:
  provider: releases
  api_key:
    secure: XCPUdDHpMyVtdKN2odttwBF3Avc2dxRySZqqTMWU09UOkJfhaiWNitrNhGQTdSzQM+iadFaLPgLfyEKwRPKQWfUbm21oO3XthbljaEssb1WvM8mktHK36m8Vg8RrbhrUNZfugVzdMKz8vU1rpobTYaHY6BQWG8Waj1jVWqyDS2VSoE/FHTq6rz9NEQ/xqzYPevOquBktpiPHEjHdinfOe0u78TszLucUm7xvF6s0mDuNaJ+ln6R5GZUj8r8D2z8W/GEJp6KyqLBOUYZ0KyteTrYMoSeisaJSq6frvLlujJWdi8/ddhjNnDQC5aw+erhyGxRamUO8id3296ZS6IAOaZJXa1K4g/7Pc31z8dhCkF0y/Ca7b2vwel/t7Qvpw7b8xHsIrJ4kXtAUEG3baRY8UjnuG+6NmoayuMWhORoOLxxK4sY5rxMkoLN3QuBef7IESb//qy6WJB66FcEGuuyjTRCx7p5UrbuY9Q74lJ10r157tziXImrWdC2sXOUARKp68lrbkNbwoaeupnCk6WnCN73cTDIyKhExqIATyd7icD7oKd8HiDiPrqgKujTNmVEiOS6594+JKxWRCG2Z8NIKKK+PPVBPI259SeoBfohEcCdEI5l9Zem/AuIw8MQYUSOnr/PorSRseP5B+/L7KFc298cucYqBSTa5VWB4GEck2Z0=
  file: "$TRAVIS_BUILD_DIR/whiteboard.zip"
  on:
    tags: true
