const BATTERY_LEVEL_REQUEST = 'clicker/battery-level/REQUEST'
const BATTERY_LEVEL_RESPONSE = 'clicker/battery-level/RESPONSE'
const BUTTON_EVENT = 'clicker/button/EVENT'
const GIT_UPDATES_REQUEST = 'clicker/git/UPDATES_REQUEST'
const GIT_UPDATES_RESPONSE = 'clicker/git/UPDATES_RESPONSE'
const GIT_PULL = 'clicker/git/PULL'
const GIT_PULL_RESPONSE = 'clicker/git/PULL_RESPONSE'

const messageTypes = [
  BATTERY_LEVEL_REQUEST,
  BATTERY_LEVEL_RESPONSE,
  BUTTON_EVENT,
  GIT_UPDATES_REQUEST,
  GIT_UPDATES_RESPONSE,
  GIT_PULL,
  GIT_PULL_RESPONSE,
]

module.exports = {
  BATTERY_LEVEL_REQUEST,
  BATTERY_LEVEL_RESPONSE,
  BUTTON_EVENT,
  GIT_UPDATES_REQUEST,
  GIT_UPDATES_RESPONSE,
  GIT_PULL,
  GIT_PULL_RESPONSE,
  messageTypes,
}