module.exports = {
  PRESS: 'PRESS',
  BATTERY_REQUEST: 'BATTERY_REQUEST',
  BATTERY_RESPONSE: 'BATTERY_RESPONSE',
  TEACHER_STATE: 'TEACHER_STATE',
  TEACHER_SYNC_ENABLE: 'TEACHER_SYNC_ENABLE',
  TEACHER_SYNC_FIRST_CLIENT: 'TEACHER_SYNC_FIRST_CLIENT',
  TIME: 'TIME',
}