 export const PRESS = 'PRESS';
 export const BATTERY_REQUEST = 'BATTERY_REQUEST';
 export const BATTERY_RESPONSE = 'BATTERY_RESPONSE';
 export const TEACHER_STATE = 'TEACHER_STATE';
 export const TEACHER_SYNC_ENABLE = 'TEACHER_SYNC_ENABLE';
 export const TEACHER_SYNC_FIRST_CLIENT = 'TEACHER_SYNC_FIRST_CLIENT';
 export const TIME = 'TIME';
